[modules]
left = [ [ "Workspaces"], "SystemInfo" ]
center = [ "WindowTitle" ]
right = [ "Tray", [ "Clock", "Privacy", "Settings" ] ]

[settings]
audio_sinks_more_cmd = "kitty wiremix --tab output"
audio_sources_more_cmd = "kitty wiremix --tab input"
